/**
 * WebSocket protocol types — shared contract between the standalone server
 * (ClientAdapter) and the VS Code extension client (VsCodeExtensionClient).
 *
 * WHAT: Pure TypeScript discriminated unions for every message that flows
 *       over the WebSocket connection.
 * WHY:  Both sides import from this single file so the protocol stays in sync.
 *       No logic lives here — only types.
 * WHEN: Imported at compile time by ClientAdapter and VsCodeExtensionClient.
 */

import { StopEvent } from '../ISessionAdapter';

// ── Server → Extension (commands) ────────────────────────────────────────────

interface WsCommandBase {
  kind: 'command';
  /** UUID generated by the server per call — echoed in the response. */
  requestId: string;
}

export interface WsCmdStartDebugging   extends WsCommandBase { type: 'startDebugging';   configName: string; }
export interface WsCmdStopDebugging    extends WsCommandBase { type: 'stopDebugging'; }
export interface WsCmdRestartDebugging extends WsCommandBase { type: 'restartDebugging'; }
export interface WsCmdSendExecution    extends WsCommandBase { type: 'sendExecution';    cmd: 'continue' | 'next' | 'stepIn' | 'stepOut'; }
export interface WsCmdSendUntil        extends WsCommandBase { type: 'sendUntil';        file: string; line: number; }
export interface WsCmdSendJump         extends WsCommandBase { type: 'sendJump';         file: string; line: number; }
export interface WsCmdEvaluate         extends WsCommandBase { type: 'evaluate';         expression: string; frameId: number; context?: string; }
export interface WsCmdScopes           extends WsCommandBase { type: 'scopes';           frameId: number; }
export interface WsCmdVariables        extends WsCommandBase { type: 'variables';        variablesReference: number; }
export interface WsCmdAddBreakpoint    extends WsCommandBase { type: 'addBreakpoint';    file: string; line: number; condition?: string; enabled?: boolean; }
export interface WsCmdRemoveBreakpoint extends WsCommandBase { type: 'removeBreakpoint'; file: string; line: number; }
export interface WsCmdListSessions     extends WsCommandBase { type: 'listSessions'; }

export type WsCommand =
  | WsCmdStartDebugging | WsCmdStopDebugging | WsCmdRestartDebugging
  | WsCmdSendExecution  | WsCmdSendUntil     | WsCmdSendJump
  | WsCmdEvaluate       | WsCmdScopes        | WsCmdVariables
  | WsCmdAddBreakpoint  | WsCmdRemoveBreakpoint | WsCmdListSessions;

// ── Extension → Server (responses + events) ──────────────────────────────────

/** Successful response to a WsCommand. */
export interface WsOkResponse {
  kind: 'response';
  requestId: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  payload: any;
  ok: true;
}

/** Error response to a WsCommand. */
export interface WsErrResponse {
  kind: 'response';
  requestId: string;
  error: string;
  ok: false;
}

export type WsResponse = WsOkResponse | WsErrResponse;

/**
 * Proactive event pushed by the extension when the debugger stops or exits.
 * No requestId — the server's ClientAdapter subscribes to these independently.
 */
export interface WsStoppedEvent {
  kind: 'event';
  type: 'stopped' | 'exited';
  payload: StopEvent;
}

/** Sent once by the extension immediately after the WebSocket connection opens. */
export interface WsRegister {
  kind: 'register';
  version: string;
}

export type WsClientMessage = WsResponse | WsStoppedEvent | WsRegister;
export type WsServerMessage = WsCommand;
